registry:
  username: eureka
  password: password
  port: 8010


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://${registry.username}:${registry.password}@localhost:${registry.port}}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${server.port}-${random.value}
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}


management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: '*'
