spring:
  application:
    name: gateway
  security:
    user:
      name: admin
      password: password
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8080

zuul:
  ignored-services: '*'
  ignored-patterns:
  - '/**/actuator/**'
  - '/actuator/**'
  host:
    max-per-route-connections: 100
    max-total-connections: 1000
    socket-timeout-millis: 50000
    connect-timeout-millis: 3000
  semaphore:
    max-semaphores: 500
  routes:
    productservice:
      path: /product/**
      serviceId: product-service
      sensitiveHeaders:
    orderservice:
      path: /order/**
      serviceId: order-service
      sensitiveHeaders:

#test:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    listOfServers: http://localhost:8881/
#    ConnectTimeout: 1000
#    ReadTimeout: 3000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100

ribbon:
  eager-load:
    enabled: true
    clients: product-service,order-service